name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: checkstyle --dry-run -Prepro.exclude.tasks=false --no-configuration-cache
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: checkstyle --dry-run -Prepro.exclude.tasks=true  --no-configuration-cache
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: checkstyle --dry-run -Prepro.exclude.tasks=false --configuration-cache
    - uses: gradle/gradle-build-action@v2
      with:
        ## XXX: issue happens here
        arguments: checkstyle --dry-run -Prepro.exclude.tasks=true --configuration-cache
